### ISSUE TITLE
Add Documentation for Wifi/Editor access

### ISSUE THREAD

**Issue by Hennoloe** [sieren/Homepoint#100]
Cant figure out where to set option ledPinPullup

**Comment by sieren** [comment]
You need to connect to the open Wifi that gets created (HomePoint-Config) and open http://192.168.99.1 to access the config

Looks like this is missing from the README (it's usually shown on display so I can see where the confusion comes from)

**Comment by Hennoloe** [comment]
The ESP Chip is already configured, and is in my Network. Already did the steps you did in the Video, by adding the Text for MQTT and so on.
but my display i think got the ledPinPullup the wrong way, because i cant see anything.

**Comment by sieren** [comment]
I see.
Here's an example that seemed to have worked:
https://github.com/sieren/Homepoint/issues/91#issuecomment-617338120

**Comment by Hennoloe** [comment]
I already did that, but im not sure what this function does.
on my ESP32 Board the blue LED is blinking right when i touch the Panel, so i think that works.
but i dont get any image.

**Comment by sieren** [comment]
If you flashed with the Generic ESP32 Image, please check the wiring instructions here:https://github.com/sieren/Homepoint/wiki/Hardware

(Specifically the PinOut and ArduiTouch Wiring as references)

**Comment by Hennoloe** [comment]
I dont know what im doing wrong, the display is white but nothing appears on it.

**Comment by Hennoloe** [comment]
I saw an Issue #73 , where someone added the extra resistor and bc557 transistor to fix it.
I think i need this too.
Just wired LED pin to 3,3v, and it works
