### ISSUE TITLE
Icon and German

### ISSUE THREAD

**Issue by Obelix411** [sieren/Homepoint#109]
it is also possible to include your own icons

it is also possible to use German words e.g. Wohnwand 

translated with Google translator

**Comment by sieren** [comment]
Ja zu beidem ;)
Die Beschreibungen der Szenen muss man als User sowieso selber angeben.
Die Icons kann man auch austauschen.

Beispiel:
```
{
    "name": "Bedroom",
    "type": "Sensor",
    "icon": "door",
    "devices": [{
      "name": "Temperature DHT Sensor",
      "type": "singleValue",
      "jsondata": true,
      "firstIcon": "temperature_small",
      "firstKey": "temperature",
      "getTopic": "bedroom/esptemp"
    }
```

Hier heißt das icon `door`, Homepoint sucht dann nach `door_active.jpg` und `door_inactive.jpg`.

**Comment by Obelix411** [comment]
Vielen Dank für die schnelle Antwort und den deutschen Support bin ein Anfänger und versuche mich ranzulassen

**Comment by Obelix411** [comment]
Hi und einen schönen Sonntag ich weis nicht ob du mir helfen kannst ich habe grade einen Temperatursensor angelegt in deiner Software jetzt bekomme ich keine Daten zu ihm hin ich arbeite mit iobroker kannst du mir da helfen?

**Comment by sieren** [comment]
Hey, da kenne ich mich leider nicht mit aus. Home point nutzt MQTT als Protokoll.
Häufige Fehlerquelle dort ist dass mqtt topics groß/Kleinschreibung-sensitive sind, sprich auf die groß und kleinschreibung geachtet werden muss.
Dann ist auch zu beachten ob die Temperatur Daten direkt über das topic gehen (zb als float) oder als JSON.

**Comment by Obelix411** [comment]
So es hat geklappt habe die zeile mit jsondata raus genommen

**Comment by Obelix411** [comment]
Eine frage habe ich noch wie klappt das mit den unter menüs also mit den 3 punkten
