### ISSUE TITLE
could not get mqtt value

### ISSUE THREAD

**Issue by ExPalm** [sieren/Homepoint#117]
Hello Sieren,

thank you for this very nice project. I could run switches by using the ArduiTouch device but unfortunately I could not find a way to show values from my ESP sensors. I use Mosquitto as MQTT Broker. Devices are sending from FHEM and I can get the values with an ESP/OLED device but I could not find a way to confinger the config.json tho get the values on the AduiTouch. 
For example I can get values by using other devices by using the gettopic /draussen/temperature. When I put this topic in the
config.json like this  
       "type": "singleValue",
      "firstIcon": "temperature_small",
      "jsondata": true,
      "firstKey": "Temperature",
      "getTopic": "/draussen/temperature"
I get only 0 displayed. 
Do you have a hint for me?

Thanks

ExPalm

**Comment by sieren** [comment]
In this particular case, what does `/draussen/temperature` actually return? Is it a JSON String (e.g. `{ "Temperature": 12 }`) or the raw value?
If it's the raw value, you need to remove `jsonData` and `firstKey` from the config.

**Comment by koenvervloesem** [comment]
Are you sure your MQTT topic is `/draussen/temperature`? MQTT topics don't start with `/` like file paths.

**Comment by ExPalm** [comment]
Here is a screenshot from MQTT Explorer. It looks for me like a raw value but when I remove  jsonData and firstkey only the icon is shown on the display. 
<img width="1013" alt="Bildschirmfoto 2020-10-27 um 12 19 02" src="https://user-images.githubusercontent.com/73529323/97294917-edbc7a00-184e-11eb-9ad3-e59cea2b08da.png">

**Comment by sieren** [comment]
It looks to me its a combination of what @koenvervloesem and I said.
The path of this topic is a bit odd to me too. Is there a blank space before the first `/` ?

**Comment by ExPalm** [comment]
No there is no space in front. Here is a screenshot from FHEM where I defined the MQTT Bridge
<img width="699" alt="Bildschirmfoto 2020-10-27 um 12 27 10" src="https://user-images.githubusercontent.com/73529323/97295652-e0ec5600-184f-11eb-8e63-483ff4e3eefe.png">
Even when I take off the first / there nothing displayed only the icon

**Comment by ExPalm** [comment]
Thank you I got it. It was the issue with the raw data. Thanks a lot and enjoy the coffee

**Comment by sieren** [comment]
Nice! Glad you got it sorted. What issue was it exactly? Always keen to learn in case someone else has this issue

**Comment by ExPalm** [comment]
The hint to remove jsonDate and firstKey when only raw data are transfered was the solution
