### ISSUE TITLE
Invert option for TFT_LED

### ISSUE THREAD

**Issue by maxl95** [sieren/Homepoint#118]
First of all, this project is amazing and works like charm.

Now my question:
Is it possible to add an option to invert the backlight? 
My backlight needs HIGH state to activate.

regards

**Comment by sieren** [comment]
Hey,

thanks a lot.
Did you try this one yet in the config file? (See Hardware under Configuration: https://github.com/sieren/Homepoint#configuration )
 
(
"ledPinPullup" | Boolean | true or false - control backlight power which can be pull-up/down depending on unit
-- | -- | --

**Comment by maxl95** [comment]
Thanks for your replay,

yes, I've already tried that. Unfortunately, the backlight is always off. I need to put the TFT_LED pin on VCC so that the backlight comes on.

**Comment by sieren** [comment]
If youre using the esp-generic build of Homepoint I could recommend checking the wiring schematics in the wiki: https://github.com/sieren/Homepoint/wiki/Hardware

**Comment by sieren** [comment]
Stale
