### ISSUE TITLE
How to flash OTA?

### ISSUE THREAD

**Issue by zejulio** [sieren/Homepoint#139]
Hello,

How to flash the OTA firmware?

Thanks!

**Comment by sieren** [comment]
There's a button in the web ui for homepoint:

<img width="833" alt="Screenshot 2021-01-18 at 18 00 51" src="https://user-images.githubusercontent.com/5174440/104944202-26d03a80-59b7-11eb-9de1-025c2823308e.png">

**Comment by zejulio** [comment]
I press that button and got "page isn't working". I only folowed the steps on main page, I think they are not up to date cause there is no information about OTA, and how to flash the OTA bin file... (I'm sorry I'm new to ESP32 and don't know how to do it...)

**Comment by sieren** [comment]
Ah, I see. Please click on "Choose File" first and select the OTA file. then press update firmware.
But good you brought it up, I feel like this needs better explanation.

**Comment by zejulio** [comment]
Duh, now I understand!
I thought it should open a new page and then I select the file...
I think this being in the same "line" as "reload/reboot" makes it messy an can get some confusion...
Thanks!

**Comment by sieren** [comment]
<img width="752" alt="Screenshot 2021-01-18 at 19 38 54" src="https://user-images.githubusercontent.com/5174440/104952466-cea03500-59c4-11eb-8876-99768874c672.png">
 

Made some changes for the next update :) Thanks!

**Comment by zejulio** [comment]
I would push update firmware below the configuration, since when you are configurating you do not want to scroll down too much (OTA takes too space on the page), or move it to a different page (like tasmota guys do).
But indeed this way is better and no confusion now.

**Comment by sieren** [comment]
Good call! Will do that

**Comment by zejulio** [comment]
So when will it be a new version? :)

**Comment by sieren** [comment]
Soon :)
