### ISSUE TITLE
Can't change config!

### ISSUE THREAD

**Issue by robgardien** [sieren/Homepoint#144]
When I try to change the config, I get the error message:

Configuration Invalid! Login via browser Could not parse config file!

The file dissapears and there is no config file left! Please help

**Comment by sieren** [comment]
Did it disappear after you logged in?

It could be related to https://github.com/sieren/Homepoint/issues/87

**Comment by kraus-wagner** [comment]
I have the same problem.
When there is an error in the config file, after a "reload" the display shows "Configuration invalid! ..."
It seems that the config.json then is locked.
It can not be edited anymore.

**Comment by sieren** [comment]
See https://github.com/sieren/Homepoint/issues/87
