### ISSUE TITLE
background color / brightness 

### ISSUE THREAD

**Issue by ghosty-be** [sieren/Homepoint#152]
On the pictures you posted of the m5stack core you seemingly have a blue or dark background with lighter pictures and text, but for some reason I have a white background with black text/images (running the current binary version 0.07.2) and its extremely bright... 
is that a setting I can fix in the config.json somehow?

**Comment by sieren** [comment]
You can set `"displayColorInverted": true` in the config json (or false, depending on what is showing) as a workaround.

I'll fix this in the next update.

**Comment by ghosty-be** [comment]
Cool! that's way better for the eyes! :)
"displayColorInverted": true
worked 
(I had to reboot to activate that setting)
