### ISSUE TITLE
Installation documentation update: esptool -b 921600 is way faster

### ISSUE THREAD

**Issue by ghosty-be** [sieren/Homepoint#156]
according to the docs esptool itself only writes at 115200 baudrate...
$ esptool write_flash -fs 4MB -fm dout 0x0 homepoint_m5stack_full.bin
...
Wrote 3842048 bytes at 0x00000000 in 365.9 seconds (84.0 kbit/s)...
$ esptool -b 921600 write_flash -fs 4MB -fm dout 0x0 homepoint_m5stack_full.bin
...
Wrote 3842048 bytes at 0x00000000 in 68.1 seconds (451.3 kbit/s)...
that's a significant speed gain my idea
my hardware plaform is m5stack core esp32

**Comment by sieren** [comment]
Good catch! :)

Feel free to do a PR updating the documentation I'll gladly merge it

**Comment by sieren** [comment]
Thanks for the PR :)
