### ISSUE TITLE
Homepoint running on Wemos D1 Mini?

### ISSUE THREAD

**Issue by detafun** [sieren/Homepoint#160]
Hallo,
ich hoffe es kann auch Deutsch verstanden werden? 
Läuft Homepoint auf einen Wemos D1 Mini?
Kann es mit ioBroker verbunden werden?

**Comment by htvekov** [comment]
Hi' @detafun

You'll need an ESP32 (Wemos D1 (mini) ESP32, Nodemcu or similar) to run HomePoint.
A Wemos D1 mini is the common name for the older ESP8266 device.
Some call the new Wemos D1 ESP32 as a mini as well, so using name alone can be confusing.
Look at the ESP on you device if in doubt.
It has to be an ESP32 WROOM or ESP32 WROVER.

Ciao !

**Comment by sieren** [comment]
Thanks @htvekov for the thorough explanation.
