### ISSUE TITLE
Problem with the beeper and ArduiTouch

### ISSUE THREAD

**Issue by THBSLtd** [sieren/Homepoint#168]
Hello, 

I installed the last firmware version (0.07.2, ESP32, ArduiTouch) and since then the buzzer has stopped working. Do you have any ideas how I can solve the problem? Or does the ArduinoTouch only work with a special firmware? 

Thank you so far, best regards

Christian

**Comment by sieren** [comment]
Hey,

It's indeed a bug. Will be fixed in the next release https://github.com/sieren/Homepoint/pull/166

**Comment by THBSLtd** [comment]
Perfekt, till then i use the Version 0.06, that one works with the ArduiTouch and the buzzer :-)

Thank you for your help :-)
