### ISSUE TITLE
Not compiling ESP32+ILI9341 

### ISSUE THREAD

**Issue by konzolec** [sieren/Homepoint#17]
Default User_Setup.h works out of the box but i want to use ESP32+ILI9341 ( https://www.aliexpress.com/item/32960934541.html ))

This is my User_Setup.h: https://pastebin.com/Qfx258Ua

Error log: https://pastebin.com/h8XB2r0B

Suggestions?

**Comment by sieren** [comment]
I think you need to define `TFT_LED` which should be the same as `TFT_BL` which is the PIN that powers the backlight, for the screensaver to kick in.
