### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by muaaz1** [sieren/Homepoint#30]
Hi there, may i know how u add the icons ? Like living room, bedroom icon? 
im still newbie in uploading images into m5stack so can you help me?

**Comment by sieren** [comment]
Take a look at the `data` subfolder and make sure to name your images accordingly to the others. Then you can just use then as an `icon` inside the `config.json`.

Images and configuration get copied into the filesystem as part of the `make spiffs_spiffs_bin` build command. Make sure to flash after :)

**Comment by muaaz1** [comment]
thank you for your help. 
btw, i have already found the filesystem folder, but may i know how to flash it? is it by running the file from command prompt?

**Comment by sieren** [comment]
You simply run `make spiffs_spiffs_bin` before `make flash`. 
make spiffs_spiffs_bin generates the .bin file which represents a separate partition which will be flashed during `make flash`. If you want to learn more about SPIFFS and flashing I recommend the ESP-IDF documentation :)

**Comment by muaaz1** [comment]
is the ESP-IDF documentation is this link?
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/storage/spiffs.html

**Comment by muaaz1** [comment]
the **make spiffs_spiffs_bin** is located in folder? or i have to install any package first?

**Comment by sieren** [comment]
There are some detailed build instructions in the README file of this repo :) If you follow those you can run `make spiffs_spiffs_bin`... spiffs_spiffs_bin is just a command for the makefile.

**Comment by muaaz1** [comment]
oh okay2 thank you very much for your help sieren. Im really new to this. Will try my best

**Comment by sieren** [comment]
No worries. Try googling for some `cmake` and `makefile` tutorials to maybe get a better understanding of how a build-system works. I think that might help :) I'll close this for now.
