### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by trommegutten** [sieren/Homepoint#40]
Hi Mathias,
This seems like a great project!
What hardware do I need to get the touch screen version inside a 55mm frame like this:
https://www.kickstarter.com/projects/159751026/23-smarthome-touch-display-w-wlan-for-55mm-switch-series

This?
https://www.aliexpress.com/item/32686606946.html?spm=a2g0o.productlist.0.0.c8853eb4s32QpF&algo_pvid=a0706732-3dc5-4b89-b2e4-b88ad275c805&algo_expid=a0706732-3dc5-4b89-b2e4-b88ad275c805-2&btsid=cc3074c7-3124-457b-aca0-264537d1dd07&ws_ab_test=searchweb0_0,searchweb201602_4,searchweb201603_53
and this?
https://www.aliexpress.com/item/4000155919030.html?spm=a2g0o.detail.1000014.5.79935fe3MAbmhg&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.13338.128125.0&scm_id=1007.13338.128125.0&scm-url=1007.13338.128125.0&pvid=be76ea54-e195-41db-82d4-3f79e4312980

can you guide me to buy the right ones?

BR,
Jarle

**Comment by sieren** [comment]
Hey,

the first one should definitely work.
Homepoint is using https://github.com/Bodmer/TFT_eSPI to drive the displays.
```with drivers for ILI9341, ILI9163, ST7735, S6D02A1, ILI9481, ILI9486, ILI9488, HX8357D and ST7789 based TFT displays that support SPI.```

so any of these will probably work with some tweaking, however I think I do support the ILI9341 out of the box as it's the same display as in ArduiTouch
