### ISSUE TITLE
GPIO pins

### ISSUE THREAD

**Issue by konzolec** [sieren/Homepoint#56]
A question, not an issue.

In readme you're referring to GPIO pins?

5 = G5 (on pic) = GPIO5
etc..

+-----------+-----+
|   TYPE    | PIN |
+-----------+-----+
| TFT_CS    |   5 |
| TFT_DC    |   4 |
| TFT_MOSI  |  23 |
| TFT_SCLK  |  18 |
| TFT_RST   |  22 |
| TFT_MISO  |  19 |
| TFT_LED   |  15 |
| TOUCH_CS  |  14 |
| TOUCH_IRQ |   2 |
+-----------+-----+

**Comment by sieren** [comment]
Yeah.. those are refering to the GPIOs :)

**Comment by konzolec** [comment]
Ok, re-checking wiring... 🏁
