### ISSUE TITLE
How long does it last on battery? 

### ISSUE THREAD

**Issue by AnderssonPeter** [sieren/Homepoint#57]
Have you tried it with the https://m5stack.com/products/battery-module and how long does it last?

**Comment by sieren** [comment]
Yeah, I have. It doesn't really last very long. I haven't optimised HomePoint for low battery consumption either and I guess you could squeeze a few hours more out of it but I doubt it'll be a pleasant experience on battery.

**Comment by AnderssonPeter** [comment]
Thanks for your response you saved me some bucks!
