### ISSUE TITLE
[Feature Request] ADD Home-Assistant 

### ISSUE THREAD

**Issue by thundergreen** [sieren/Homepoint#71]
Dear Dev. That's the most genial Project for me to use it as a small touch panel to control my AC in each room. Unfortunately I use Home-Assistant. Do you plan to make it also running for Home Assistant?

**Comment by sieren** [comment]
I'm afraid not for now. I'm working on Hue integration next, HomeAssistant would mean lots more work and on top of that I'm unfortunately not overly familiar with the platform.

**Comment by sieren** [comment]
Did you consider using the MQTT Module in Home Assistant to talk to HomePoint?

**Comment by thundergreen** [comment]
Yes I do :)

**Comment by blackout314** [comment]
> 
> 
> Dear Dev. That's the most genial Project for me to use it as a small touch panel to control my AC in each room. Unfortunately I use Home-Assistant. Do you plan to make it also running for Home Assistant?

and, it works?

**Comment by cbrightly** [comment]
@thundergreen What doesn’t currently work with Home Assistant? If you have an MQTT integration, it can be set up to have the Homepoint device discovered automatically, correct?

**Comment by sieren** [comment]
Closed, discussion moved to https://github.com/sieren/Homepoint/issues/130
