### ISSUE TITLE
Add icons and def.

### ISSUE THREAD

**Issue by llevet** [sieren/Homepoint#75]
Please, could you add icons and definitions for :

light : 
bulb_active.jpg
bulb_inactive.jpg

atmospheric pressure (i use bosch BME280 : humidity, barometric, temperature) :
pressure_small.jpg

Thanks.

**Comment by sieren** [comment]
Hey,

The next HomePoint Release will have fully configurable Icons in the Config file, thus getting rid of the need to hardcore this:
https://github.com/sieren/Homepoint/pull/66

I might release new binaries later today or tomorrow.

**Comment by sieren** [comment]
https://github.com/sieren/Homepoint/releases/tag/v0.02
