### ISSUE TITLE
Add wake up screen on change state

### ISSUE THREAD

**Issue by llevet** [sieren/Homepoint#76]
Hi,
Please add the possibility to wake up the screen when a change status is detected on a item (change value of getTopic)  : 

...
{
      "name": "Porte 1",
      "setTopic": "dumy/garage/porte/status/set",
      "getTopic": "dumy/garage/porte/status",
      "onValue": "on",
      "offValue": "off",
      "screenOn": "true"
	},
....

Thanks.

**Comment by sieren** [comment]
This should already be the case for all switches.

**Comment by llevet** [comment]
Excuse me ! 
It is working like that !
Cool !
