### ISSUE TITLE
Bulb icons

### ISSUE THREAD

**Issue by llevet** [sieren/Homepoint#79]
This is my bulb for the project.
bulb_active.jpg
bulb_inactive.jpg

Thanks.
![bulb_active](https://user-images.githubusercontent.com/13711825/78723010-ea9d8300-792a-11ea-9c24-e2a3573c390b.jpg)
![bulb_inactive](https://user-images.githubusercontent.com/13711825/78723023-ef623700-792a-11ea-8ae2-9416e17e77a2.jpg)

**Comment by quotschmacher** [comment]
maybe you shoul make a pull request @llevet . i like the bulb.
