### ISSUE TITLE
Change bin_address in build_all script

### ISSUE THREAD

**Issue by MLindek** [sieren/Homepoint#82]
hi matt, 
thanks for setting up the partion table, now it works. 
But please make a small change for everyone who uses the build_all script.
There the lines with the Python call must be changed  from 
--bin_address 0x8000 0x1000 0x10000 0x310000 
to
 --bin_address 0x8000 0x1000 0x10000 0x360000.

**Comment by sieren** [comment]
Good catch.. fixed
