### ISSUE TITLE
screenRotationAngle seems not to work

### ISSUE THREAD

**Issue by franki29** [sieren/Homepoint#84]
HI, i am using the newest recompile version for the esp generic. As my Touchscreen seems to "rotated" i tried the command screenRotationAngle in the json config file , but no change. No,matter what value i am using.

I tried with "screenRotationAngle": "2", , but maybe I do something wrong?

Thanks for helping
Frank

**Comment by sieren** [comment]
@franki29 thanks for the swift report. Was able to replicate this issue and just published a new release: https://github.com/sieren/Homepoint/releases/tag/v0.03
