### ISSUE TITLE
Error Message "Unable to convert screenRotationAngle"

### ISSUE THREAD

**Issue by franki29** [sieren/Homepoint#86]
Hi , thanks for the new Version. Using "screenRotationAngle": "3" or other value, cause a Error message at the screen :  "Unable to convert screenRotationAngle"

What I am doing wrong?

Mfg
Frank

**Comment by sieren** [comment]
Hey, this has to be an integer, not a string. So `"screenRotationAngle": 3` would be the way to go :)

**Comment by franki29** [comment]
Stupid me, yes now it is working.
Thanks for helping
