### ISSUE TITLE
Sensors connected to ESP32

### ISSUE THREAD

**Issue by ben-bole** [sieren/Homepoint#93]
Hello,
I am using an ESP32 in the ArduiTouch Housing! It works perfectly! Thank you for this great piece of code.
Because my ArduiTouch is placed in the Bathroom to control the lights, I thought about measuring the temperature and humidity to know when I need to open the window!
Is there any opportunity to connect a sensor (e.g. DHT 22) directly to the ESP32 where Homepoint runs on. My idea would be to copy the needed library to the library folder, compile it by oneself, and then have the possibility to configure the library in the config.json file!

It would be great if something like this would be possible in the future!

**Comment by sieren** [comment]
Hey,

I think that's tricky, architecturally speaking. 
Right now each sensor has to be a MQTT device, but I have vague plans for the future to have it ra bit more abstract so the things being shown on display could come from any source (MQTT, Hue, HomeKit or even custom sensor events).

Until then I'm afraid it's probably a bit tricky to add a custom one (I guess you could subclass one of the UIWidgets and hardcore-hack one in there).

But thanks for the suggestion! I'll keep this as a potential usecase in mind :)
